plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.usimsfix'
    compileSdk 35

    defaultConfig {
        applicationId "io.github.usimsfix"
        minSdk 28
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    compileOnly 'io.github.libxposed:api:102.0.0-SNAPSHOT'
}
